services:
  - type: web
    name: onvaou-api
    env: python
    rootDir: backend
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: onvaou-db
          property: connectionString
      - key: SECRET_KEY
        value: <ta_clé_secrète>
